package com.ven.leetcode.sepchallenge;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input: s = "abcd" t = "abcde"
 * 
 * Output: e
 * 
 * Explanation: 'e' is the letter that was added.
 * 
 * @author Venkatesh Manohar
 *
 */
public class FindtheDifference {
	public char findTheDifference(String s, String t) {
        int sumS = 0, sumT = 0;
		char[] arrS = s.toCharArray();
		char[] arrT = t.toCharArray();
		for (int i = 0; i < arrS.length; i++) {
			sumS += arrS[i] - 'a';
			sumT += arrT[i] - 'a';
		}
		sumT += arrT[arrT.length - 1] - 'a';
		return (char) (sumT - sumS + 'a');
	}
	
	public static void main(String[] args) {
		FindtheDifference f = new FindtheDifference();
		System.out.println(f.findTheDifference("abcd", "abcde"));
		System.out.println(f.findTheDifference("aaaabbbbbccccdddgdd", "bbbbbdddaaaaccccgdd"));
	}
}
